name: file-sharing
services:
    database:
        image: mariadb:11
        env_file:
            - ./.env
        volumes:
            - ./init:/docker-entrypoint-initdb.d
            - db_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: "file-sharing"
        healthcheck:
          test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized"]
          start_period: 5s
          start_interval: 10s
          interval: 5s
          timeout: 5s
          retries: 3


    backend:
        build:
          context: ./backend
          dockerfile: Dockerfile
        volumes:
          - ./backend:/usr/src/app
          - backend_node_modules:/usr/src/app/node_modules
          - ./backend/upload:/usr/src/app/upload


        environment:
          - NODE_ENV=${NODE_ENV}
          - DB_HOST=${DB_HOST}
          - DB_USER=${DB_USER}
          - DB_PASSWORD=${DB_PASSWORD}
        ports:
          - "4040:4040"
        depends_on:
          database:
            condition: service_healthy


    frontend:
        build:
          context: ./frontend
          dockerfile: Dockerfile
        environment:
          - NODE_ENV=${NODE_ENV}
        volumes:
          - ./frontend:/usr/src/app
          - frontend_node_modules:/usr/src/app/node_modules
        ports: 
          - "5173:5173"

volumes:
  db_data:
  backend_node_modules:
  frontend_node_modules:
