name: file-sharing
services:
    database:
        image: mariadb:11
        env_file:
            - ./.env
        volumes:
            - ./init:/docker-entrypoint-initdb.d
            - db_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: "file-sharing"
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${DB_PASSWORD}"]
            interval: 5s
            timeout: 5s
            retries: 5


    backend:
        build:
          context: ./backend
          dockerfile: Dockerfile
        volumes:
          - ./backend:/usr/src/app
          - backend_node_modules:/usr/src/app/node_modules
        environment:
          - NODE_ENV=${NODE_ENV}
        depends_on:
          - database:
            condition: service_healthy


    frontend:
        build:
          context: ./frontend
          dockerfile: Dockerfile
        environment:
          - NODE_ENV=${NODE_ENV}